import BridgeAgentCore

extension DeepSeekHarnessACPProvider {
  public static let capabilitySnapshot = AgentCapabilitySnapshot(
    advertised: [
      .sessionCreate,
      .interrupt,
      .steer,
      .steerInterruptAndContinue,
      .textDelta,
      .toolLifecycle,
      .workspaceRead,
      .workspaceWriteInPlace,
      .oneShotApproval,
      .structuredApprovalPayload,
      .modelSelection,
      .effortSelection,
      .shell,
      .webSearch,
      .webFetch,
      .codeExecution,
      .subagents,
      .workflow,
      .skills,
    ],
    observed: [
      .sessionCreate,
      .interrupt,
      .steer,
      .steerInterruptAndContinue,
      .textDelta,
      .toolLifecycle,
      .workspaceRead,
      .workspaceWriteInPlace,
      .oneShotApproval,
      .structuredApprovalPayload,
      .modelSelection,
      .effortSelection,
      .shell,
      .webSearch,
      .webFetch,
      .codeExecution,
      .subagents,
      .workflow,
      .skills,
    ],
    enforced: [
      .sessionCreate,
      .interrupt,
      .steer,
      .steerInterruptAndContinue,
      .textDelta,
      .toolLifecycle,
      .workspaceRead,
      .workspaceWriteInPlace,
      .oneShotApproval,
      .structuredApprovalPayload,
      .modelSelection,
      .effortSelection,
      .shell,
      .webSearch,
      .webFetch,
      .codeExecution,
      .subagents,
      .workflow,
      .skills,
    ]
  )
}
